var addDummyFiles = function() {
	Directory.Files.push(new File("a","This is the 'a' file.\nIt has a line break."));
	Directory.Files.push(new File("b","b"));
	Directory.Files.push(new File("c","c"));
	Directory.Files.push(new File("d","d"));
	Directory.Files.push(new File("e","e"));
	Directory.Files.push(new File("f","f"));
	Directory.Files.push(new File("g", "g"));
	Directory.Files.push(new File("li", Lorem));
}

var Lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tincidunt consequat libero eget placerat. Fusce tempus sagittis justo. Integer est augue, blandit et pharetra vel, venenatis ut risus. Donec egestas libero purus, ac luctus ante malesuada sit amet. Duis vitae porttitor nibh. Aliquam et enim eget tortor pretium commodo. In lobortis, urna vel laoreet molestie, neque sapien ullamcorper odio, suscipit euismod arcu dui sit amet urna. Quisque imperdiet tincidunt hendrerit. Suspendisse potenti."
    + "Quisque sit amet purus enim. Etiam at dolor non nibh pulvinar suscipit. Nullam posuere eros massa, sit amet pharetra mi pulvinar quis. Nullam sit amet convallis turpis. Vestibulum vulputate gravida felis, id lobortis nunc fermentum vel. Suspendisse lacinia, neque ac cursus pulvinar, augue nisi commodo diam, sed pellentesque diam justo ac ante. Sed egestas mauris mauris, vitae ultricies erat dignissim sed. Nam blandit tempus tortor, eget fermentum risus faucibus at. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque tincidunt tellus malesuada libero euismod, vitae volutpat enim pharetra. Mauris sed blandit nisl. Sed sed faucibus nibh. Duis id neque posuere, interdum mi quis, finibus odio. Etiam vestibulum lacinia tellus, egestas tincidunt nisl."
    + "Maecenas pharetra lectus in sem vulputate, fringilla accumsan arcu venenatis. Fusce pretium elit eu tortor sollicitudin, elementum tempus neque fermentum. Fusce ornare eget dui sed euismod. Vivamus facilisis non mi eu pulvinar. Vivamus lobortis egestas ex, eget tincidunt felis ullamcorper sodales. Quisque sed tellus facilisis, viverra sapien eu, pellentesque nulla. Etiam in vehicula felis, at blandit leo. Donec blandit, ante non condimentum mollis, dolor massa pulvinar velit, sit amet placerat odio sem ut metus. Nulla nec convallis lorem. Curabitur sed tempus eros, non viverra nisl. Sed tincidunt efficitur purus sed semper. Nullam sit amet vulputate turpis. Integer lobortis felis eget arcu rhoncus, in vulputate massa tincidunt."
    + "Duis tincidunt enim in urna congue maximus. Vestibulum lobortis ut urna vel bibendum. Nullam congue ligula eu elit vehicula auctor. Curabitur tincidunt at justo vel condimentum. Cras sit amet lorem ullamcorper, bibendum mauris eu, congue ante. Sed placerat pretium tortor. Phasellus eu rutrum odio, in pharetra dolor. Nulla non libero dictum, varius ipsum nec, venenatis ante. Suspendisse et molestie diam. Donec ut molestie libero. Nullam quis pulvinar odio. Praesent lacinia mauris non metus varius molestie. Donec porta dui vel lacus vulputate, ac elementum sem facilisis. Integer non laoreet ante. Ut ut semper purus, vitae auctor ante."
    + "Donec varius lacus nec posuere semper. Vestibulum auctor congue maximus. Aenean in gravida ante, sed feugiat ipsum. Donec hendrerit, leo id accumsan tincidunt, ante nibh vehicula leo, eget sodales metus orci ut massa. Vestibulum in lorem mauris. Nulla ut tempor turpis. Fusce viverra ullamcorper metus, in venenatis felis pellentesque nec. Curabitur non sapien accumsan, cursus metus sed, faucibus metus. Mauris facilisis venenatis eleifend. Nam a lacus vitae est semper mollis a a leo. Fusce sed sollicitudin enim, a sodales urna. Sed scelerisque, ex sit amet tristique interdum, dolor urna consectetur diam, in dapibus risus eros pretium ex. Maecenas fermentum viverra varius. Pellentesque eget accumsan tellus."
    + "Quisque posuere at massa rhoncus facilisis. Curabitur feugiat ut eros at bibendum. Nam tincidunt sem vel ante cursus, nec iaculis augue auctor. Phasellus id dignissim nisl. Quisque facilisis pellentesque felis, id finibus tellus semper ac. Nunc vitae fringilla arcu. Donec lacinia eros et congue ullamcorper. Phasellus semper nisi eu auctor auctor. Ut sit amet nunc quis elit pharetra vehicula. Curabitur ultrices neque tincidunt dolor ullamcorper, in varius sem volutpat. Ut quis lobortis nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos."
    + "Nullam vitae vehicula elit. Vivamus ac mauris ut lorem egestas lobortis sed et nisi. Sed in ultricies nunc. Donec commodo erat sem, nec dictum neque iaculis eu. Cras dignissim cursus rutrum. Mauris imperdiet erat quis magna viverra blandit. Morbi euismod posuere velit ac semper. Phasellus vitae mauris ac lectus rhoncus feugiat. Nulla vitae turpis nec purus aliquam iaculis. Ut et erat at neque elementum consectetur. Integer ac ante ut massa ullamcorper rutrum. Morbi ultrices luctus ligula, vel consequat nulla mollis at."
    + "Sed porttitor nisi eu eros eleifend, nec scelerisque turpis elementum. Nam sollicitudin sem a enim tempus, quis euismod nibh dapibus. Nunc mi ligula, tempor non ante eget, venenatis sagittis lectus. Fusce vestibulum venenatis mi, sit amet pretium lacus. Morbi sit amet dolor quis dolor convallis posuere. Donec ac neque sed erat posuere faucibus id eu ligula. Nunc mollis lorem vitae libero aliquet, eu congue erat sagittis. Donec tristique volutpat consectetur. Fusce quis tellus iaculis, convallis justo vel, ullamcorper elit. Phasellus varius magna ut venenatis mollis. Morbi dignissim nisl sed felis porttitor placerat."
    + "Maecenas eu vestibulum lacus. Donec ut purus massa. Donec odio enim, congue quis sollicitudin id, fringilla vitae augue. Quisque nulla nisi, porttitor a diam sed, tempus ornare dui. Aliquam erat volutpat. Cras nec erat porta eros fermentum volutpat. Suspendisse sodales velit elit, a sollicitudin orci congue nec. Aenean et neque non nunc commodo vestibulum quis a orci. Pellentesque felis nunc, maximus a volutpat quis, accumsan in massa. Integer sed euismod leo. Donec dignissim enim nec convallis luctus. Quisque faucibus faucibus libero in scelerisque. Fusce mattis finibus lacus, non fringilla neque fermentum eu"
    + "Proin interdum turpis eget enim semper, in auctor orci lacinia. Nulla eget elit erat. Pellentesque sit amet luctus ante. Nullam fermentum vel massa in tempor. Etiam eu lorem eu nulla euismod posuere vehicula vel quam. Aliquam eu ultricies nunc. Duis iaculis arcu ex, a sagittis nisi fringilla sit amet. Ut ligula dui, auctor sed tortor a, semper pharetra mauris. Phasellus sapien nisi, cursus vel felis a, feugiat euismod neque."
    + "Sed et convallis arcu. Ut sodales, mi et dignissim euismod, eros tortor molestie ante, in efficitur libero nibh sit amet metus. Phasellus a tortor eget neque consequat efficitur sed eget tellus. Morbi pulvinar a nibh id tincidunt. Cras ac venenatis elit. Suspendisse ac purus tempus, fringilla tortor nec, dictum turpis. Donec scelerisque ex nec erat facilisis eleifend."
    + "Praesent non lacus vestibulum, molestie augue a, eleifend sapien. Mauris eu ipsum ullamcorper ligula vestibulum consectetur. Ut vulputate nisi eu augue vestibulum, at vehicula odio bibendum. Sed ut justo mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse ut mollis mi. Proin aliquet enim vitae leo sollicitudin sagittis. Sed blandit imperdiet cursus. Quisque dictum egestas dapibus. Duis hendrerit, eros a scelerisque sodales, nisi velit dapibus lectus, non eleifend justo nibh quis ex. Sed lobortis nisi nec magna porttitor, et suscipit magna dictum. Etiam dapibus condimentum ornare. Duis tortor leo, feugiat in massa ac, semper malesuada arcu."
    + "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas ut sem est. In sed molestie arcu, vel interdum eros. Curabitur dignissim orci justo, eget viverra nulla blandit eu. Mauris suscipit a eros rutrum vestibulum. Nulla a justo erat. Quisque magna justo, maximus vitae felis eget, auctor pretium diam. Quisque tristique sed nulla vitae gravida. Nunc est turpis, sollicitudin in sem a, hendrerit rutrum leo. Nunc porttitor tellus et molestie volutpat. Sed congue viverra ligula in aliquam. Suspendisse ornare tincidunt efficitur. Integer mollis placerat pharetra. Integer at mauris non velit ullamcorper mattis eget ac leo. Donec eleifend tincidunt nunc. Vestibulum id suscipit risus."
    + "Fusce accumsan nec mauris a hendrerit. Donec in pulvinar dolor, sed maximus purus. Phasellus finibus ut lacus sit amet vestibulum. Nunc laoreet felis sed nisl commodo accumsan. Sed vulputate lorem porta nisl placerat, id varius ligula consequat. Aenean cursus augue id sodales euismod. Phasellus odio enim, cursus nec suscipit id, efficitur quis est. Ut sapien dui, pellentesque ut ante vitae, gravida mattis mi. Nunc tristique, massa ut accumsan malesuada, tellus sapien efficitur dui, eu iaculis dolor ligula quis purus. In hac habitasse platea dictumst. Suspendisse potenti. Aliquam ac purus turpis. Nullam eu odio urna. Sed tincidunt ipsum at ex sagittis, vel dictum augue rhoncus. Praesent tempus ante vitae placerat hendrerit. Nunc nec velit elementum, porttitor dolor a, suscipit lacus."
    + "Quisque vitae lacinia arcu. Nullam eu nisi a arcu convallis sagittis. Phasellus mattis risus tortor, sit amet bibendum lectus ullamcorper vel. Praesent ac est sapien. Praesent viverra odio vitae risus condimentum, et pharetra turpis blandit. Morbi sed accumsan risus. Sed ut consequat ligula."
    + "Donec quis ante at ante auctor mattis a id dolor. Suspendisse potenti. Duis et ex in enim congue pulvinar vitae eget leo. Curabitur tempus nisl eget risus pharetra, nec scelerisque metus dictum. Pellentesque ut ultricies est. Cras pulvinar interdum risus sed egestas. Ut vehicula rutrum posuere. Fusce laoreet, eros eu malesuada cursus, dui risus scelerisque urna, sed aliquet libero nisl sed erat. Pellentesque porta purus ut massa luctus, et accumsan est volutpat. Praesent enim est, pellentesque eget tellus eu, venenatis vulputate metus. Morbi quis blandit quam. Cras ut metus sit amet quam euismod bibendum vel nec urna."
    + "Phasellus molestie mi quis diam ultrices dignissim. Integer laoreet ut nunc sit amet rhoncus. Nunc efficitur neque leo, eu posuere eros porttitor vitae. Vivamus nibh magna, eleifend quis aliquet ut, accumsan non metus. Mauris commodo condimentum sapien, nec efficitur massa lobortis quis. Quisque ac pharetra sapien. Aliquam aliquam felis eget arcu lacinia, ac egestas dolor finibus. Pellentesque id mattis tellus. Donec cursus lorem non augue tempor, vel venenatis odio vestibulum. Cras ac luctus odio. Etiam lacinia erat eu metus blandit pretium. Maecenas ut elit non lacus ultrices malesuada ac ut ipsum."
    + "Proin interdum pulvinar tortor, at congue ante euismod non. Donec lobortis scelerisque mi a laoreet. Cras blandit placerat ultricies. Praesent egestas magna ut dui dictum eleifend. Duis placerat euismod neque, sed cursus elit auctor nec. Morbi porttitor interdum lorem, id aliquet quam vestibulum quis. Vivamus porttitor lacus non nisl tristique sollicitudin."
    + "Suspendisse a dolor tempor, rhoncus metus at, sollicitudin mauris. Donec lacinia ac lorem ac ornare. Integer id dictum nisl. Nullam blandit, ligula eget ullamcorper rutrum, felis neque ultrices nisi, et convallis turpis sem vel sapien. Fusce fermentum odio et mauris pharetra, nec pharetra libero fermentum. Sed eleifend est quis erat semper, et ultricies lacus luctus. Integer eleifend lorem elit, in rhoncus tellus lobortis in. Suspendisse hendrerit, quam et gravida semper, nulla tellus venenatis ligula, at imperdiet tortor justo et nisi. Etiam finibus eros non felis varius, et commodo leo consectetur. Vestibulum purus massa, tempus nec rutrum aliquet, commodo nec ante. Ut pulvinar rhoncus orci vitae congue."
    + "Cras hendrerit sagittis sagittis. Vestibulum in magna dolor. Duis non nunc in ante imperdiet imperdiet ut ut arcu. Ut volutpat tincidunt luctus. Duis gravida enim a diam tristique maximus. Fusce nisl mauris, posuere at lacus vel, elementum accumsan nisi. Donec ultrices magna vel erat dapibus ultricies. Nam at libero imperdiet nibh hendrerit venenatis vitae id magna. Morbi a pellentesque lacus, auctor finibus magna. Quisque nec elit varius leo fringilla ornare. Proin placerat nibh et dapibus lobortis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer vel pretium diam.";